// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPWwXsmLhcRLXl-lW6ZceWFqXV-GKIZpg',
    appId: '1:66452065741:web:77d4828a83356428cf8884',
    messagingSenderId: '66452065741',
    projectId: 'iot-with-flutter-fa297',
    authDomain: 'iot-with-flutter-fa297.firebaseapp.com',
    storageBucket: 'iot-with-flutter-fa297.appspot.com',
    measurementId: 'G-98DJVP3P2Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAclDoIm8w1q_MoG2cRJxCEEaNwpl58wM0',
    appId: '1:66452065741:android:146ace605e56387dcf8884',
    messagingSenderId: '66452065741',
    projectId: 'iot-with-flutter-fa297',
    storageBucket: 'iot-with-flutter-fa297.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCwPTWEC3pysLVi_vcGJjsklGjQ1FeRvy4',
    appId: '1:66452065741:ios:293b2ce8b9546e49cf8884',
    messagingSenderId: '66452065741',
    projectId: 'iot-with-flutter-fa297',
    storageBucket: 'iot-with-flutter-fa297.appspot.com',
    iosBundleId: 'com.example.iotAndFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCwPTWEC3pysLVi_vcGJjsklGjQ1FeRvy4',
    appId: '1:66452065741:ios:293b2ce8b9546e49cf8884',
    messagingSenderId: '66452065741',
    projectId: 'iot-with-flutter-fa297',
    storageBucket: 'iot-with-flutter-fa297.appspot.com',
    iosBundleId: 'com.example.iotAndFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAPWwXsmLhcRLXl-lW6ZceWFqXV-GKIZpg',
    appId: '1:66452065741:web:f4f7bfdaa3278672cf8884',
    messagingSenderId: '66452065741',
    projectId: 'iot-with-flutter-fa297',
    authDomain: 'iot-with-flutter-fa297.firebaseapp.com',
    storageBucket: 'iot-with-flutter-fa297.appspot.com',
    measurementId: 'G-ENZ824P6XF',
  );
}
